### ISSUE TITLE
auto accept error msg

### ISSUE THREAD

**Issue by 909oce** [teisseire117/league-loader-plugins#1]
auto accept works fine, but everytime it accepts a game theres an error message from league in the top right corner, unsure why it happens, maybe accepting too fast?

**Comment by Lyfhael** [comment]
@fe1ino  What error message is it ? And do you have other plug-ins ?

**Comment by 909oce** [comment]
"An unexpected error occurred while displaying the ready check". Only other plugin is my theme changing the font and background of client.

**Comment by Lyfhael** [comment]
If you can open the console and see if a more specific error message is displayed it would be helpful to pinpoint the issue

**Comment by teisseire117** [comment]
Closing it as no answers
