### ISSUE TITLE
Display back summoner names

### ISSUE THREAD

**Issue by timonkobusch** [teisseire117/league-loader-plugins#11]
![image](https://user-images.githubusercontent.com/73612086/224157882-a96fee3b-aae2-4ad6-9590-5659e3d75cf7.png)

**Comment by timonkobusch** [comment]
Permanent error for me

**Comment by Lyfhael** [comment]
Create a file named 'config' without any extension (not .txt, not .cfg, no extension). Inside it write the following : 
```
[Main]
LeaguePath=C:\Riot Games\League of Legends
DisableWebSecurity=1
IgnoreCertificateErrors=1
RemoteDebuggingPort=8888
```
If your League of Legends path is different you can change it.

Now place the file inside your league loader folder and you're good
