### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Sheelia** [teisseire117/league-loader-plugins#2]

**Comment by teisseire117** [comment]
> ![image](https://user-images.githubusercontent.com/85132999/214434275-822d4b57-ea0b-4e84-af7c-8aff46b2f87b.png) It will be very useful if we add it, we don't have to leave client.

Added https://github.com/teisseire117/league-loader-plugins/commit/b28a733b8d9c600bc76366371bd7b04c07248b25

**Comment by Lyfhael** [comment]
> ![image](https://user-images.githubusercontent.com/85132999/214434275-822d4b57-ea0b-4e84-af7c-8aff46b2f87b.png) It will be very useful if we add it, we don't have to leave client.

Added https://github.com/teisseire117/league-loader-plugins/blob/main/plugins/dodge_button.js

![xGwVnrU](https://user-images.githubusercontent.com/43145883/214470147-77a53921-23b4-4d66-a469-6d6e01b1dc8f.png)

**Comment by Sheelia** [comment]
thanks dude 
looking forward to your next project
