### ISSUE TITLE
display back summoners only shows a black screen

### ISSUE THREAD

**Issue by Sheelia** [teisseire117/league-loader-plugins#8]
![image](https://user-images.githubusercontent.com/85132999/221669879-71abfe43-b7de-4508-ba3b-82bc95ddd514.png)

**Comment by Lyfhael** [comment]
Create a file named 'config' without any extension (not .txt, not .cfg, no extension). Inside it write the following : 
```
[Main]
LeaguePath=C:\Riot Games\League of Legends
DisableWebSecurity=1
IgnoreCertificateErrors=1
RemoteDebuggingPort=8888
```
If your League of Legends path is different you can change it.

Now place the file inside your league loader folder and you're good

**Comment by Legnatbird** [comment]
Still showing black screen, but in the logs show participants array with the summoner names

**Comment by Lyfhael** [comment]
Try naming it config.cfg maybe, it's one of the two. But if it's not that the problem, try checking the console to see if an error message is displayed

**Comment by Seiori** [comment]
Attempted this but was unable to get it to still show anything. Just to confirm where are you putthing the config file. Inside the 'display_back_summoner_names' folder or the League of Legends Path directly?

I also checked console and was getting errors on there before and after trying the config file in the plugin folder. Just grabbed the log of it and attached it.
[127.0.0.1-1678194125442.log](https://github.com/teisseire117/league-loader-plugins/files/10909626/127.0.0.1-1678194125442.log)

**Comment by Legnatbird** [comment]
![image](https://user-images.githubusercontent.com/50637445/223466542-ef05255c-dfd2-4cbd-9009-88557b0539b4.png)

Only show that, but still black (I tried the .cfg but that caused the request to fail and did not show the array with the names)

**Comment by Seiori** [comment]
If I had to guess for yours, it is just an issue with the region value not being recognized. I think in this case your region is 'LAN' right? As I was able to get a response making a request for that region through just the URL

**Comment by Lyfhael** [comment]
> If I had to guess for yours, it is just an issue with the region value not being recognized. I think in this case your region is 'LAN' right? As I was able to get a response making a request for that region through just the URL

You got that right.

His region has two abbreviation possible and porofessor chose the other one. It'll be an easy fix

**Comment by Lyfhael** [comment]
> ![image](https://user-images.githubusercontent.com/50637445/223466542-ef05255c-dfd2-4cbd-9009-88557b0539b4.png)
> 
> Only show that, but still black (I tried the .cfg but that caused the request to fail and did not show the array with the names)

Yeah keep it named config after all.

Can you download the new index.js 9f95509 and try again. I think it should be good but I've no way to test

**Comment by Legnatbird** [comment]
Now the button just disapeared

**Comment by Lyfhael** [comment]
> Now the button just disapeared

Oh yeah my bad, it's fixed now

**Comment by Legnatbird** [comment]
Works :D, ty for the attention

**Comment by Lyfhael** [comment]
> Works :D, ty for the attention

yw!
