### ISSUE TITLE
Auto-Message

### ISSUE THREAD

**Issue by myfirstevercode** [teisseire117/league-loader-plugins#9]
End game lobby where it shows the winner and loser stats

**Comment by Lyfhael** [comment]
I don't understand.

**Comment by myfirstevercode** [comment]
this lobby
![image](https://user-images.githubusercontent.com/15106245/223101026-5a96d242-0f11-41ba-a1dd-c560487f065f.png)
send message like www.twich.tv/streamer after the game before making another

**Comment by Lyfhael** [comment]
Oh I see, I think you're still using an old version of the script because it doesn't happen in the new one
